<?php

use Illuminate\Database\Seeder;

class CategorySupplierTableSeeder extends Seeder
{
    private $databaseSeederHelper = null;

    public function __construct(DatabaseSeederHelper $databaseSeederHelper)
    {
        $this->databaseSeederHelper = $databaseSeederHelper;
    }

    public function run()
    {
        $categories = [
            /*'Building materials',
            'Networking & Communication equipments',
            'Construction machinery and equipment',
            'Road construction materials',
            'Mechanical (solar and sanitary)',
            'Electrical Materials',
            'Industrial safety equipment',
            'H. Metal and industrial engineering',
            'Pre-engineering system', 'Geological',
            'Land and building development',
            'Rental',
            'Aluminium',
            'Ceramics and Sanitaries'*/
            /* 'Cement',
             'Cement Products',
             'Cold Room/Chiller/Condensing Unit',
             'Construction Chemicals',
             'Construction Machinery Spare parts',
             'Crusher Aggregate/soil Aggregates',
             'Door Looks and Accessories',
             'Dump truck Supplier',
             'Electro-mechanical work',
             'Elevator/escalator',
             'Excavation and earth moving work',
             'Exploration',
             'Floor tile',
             'Foundation',
             'Gypsum/Gypsum board',
             'hydro-Construction',
             'Interior Design and Decoration',
             'Marble and Granite',
             'Quartz and Paint',
             'Pipe and Fitting',
             'Prefabricated Building and Parts',
             'Pvc Doors, Windows and Partition',
             'Pvc pipe, Conduit and Fitting',
             'Real State',
             'Roof Tiles',
             'Solar Equipment',
             'Surveying Equipment',
             'Surveying Engineering',
             'Water Engineering and Consultancy',
             'Water meter',
             'Water proofing/Dump Proofing',
             'Water resource Development Project Study/Design/Exploration',
             'Water well Drilling',
             'Welding And machine Works',
             'Wood Works',
             'Nails',
             'Bricks',
             'Bitumen',
             'Celling',
             'Furniture',
             'Glazing',
             'Fiber Glass and Tanker'*/
           /* 'Abiy Addi',
            'Adama (Nazareth/Nazret)',
            'Addis Ababa',
            'Addis Alem (Ejersa)',
            'Addis Zemen',
            'Adet',
            'Adigrat',
            'Adwa',
            'Agaro',
            'Akaki',
            'Alaba (Kulito, Quliito)',
            'Aliten',
            'Amaro',
            'AmbaMariam',
            'Ambo',
            'Ankober',
            'Arba Minch',
            'Arboye',
            'Asaita',
            'Asella',
            'Asosa',
            'Awasa',
            'Awash',
            'Axum',
            'Alamata',
            'Aykel',
            'Babille',
            'Baco',
            'Badme',
            'Bahir Dar',
            'Bati',
            'Bedele',
            'Beica',
            'Bichena',
            'Bishoftu',
            'Bonga',
            'Burie Damote',
            'Butajira',
            'Ciro',
            'Chencha',
            'Chuahit',
            'chelenko',
            'Dessie',
            'Dabat',
            'Dangila',
            'Debarq',
            'Debre Berhan',
            'Debre Marqos',
            'Debre Tabor',
            'Debre Werq',
            'Debre Zebit',
            'Dejen',
            'Delgi',
            'Dembidolo',
            'Dessie (Dese)',
            'Dila',
            'DilYibza (Beyeda)',
            'Dire Dawa',
            'Dolo Bay',
            'Dolo Odo',
            'Durame',
            'Enijibara',
            'Finicha',
            'Fiche',
            'Finote Selam',
            'Freweyni',
            'Gondar',
            'Gambela',
            'Gelemso',
            'Ghimbi',
            'Ginir',
            'Goba',
            'Gobiyere',
            'Gode',
            'Gololcha',
            'Gondar',
            'Gongoma',
            'Gore',
            'Gorgora',
            'Harar',
            'Harar (or Harer)',
            'Harorisa',
            'Hayq',
            'Holeta',
            'Hosaena',
            'Humera',
            'Imi',
            'Jijiga',
            'Jimma',
            'Jinka',
            'Kabri Dar',
            'Kebri Mangest',
            'Kobo',
            'Kombolcha',
            'Konso',
            'Kulubi',
            'Lalibela',
            'Limmu Genet',
            'Maji',
            'Maychew',
            'Mekele',
            'Mendi',
            'Metemma',
            'Metu',
            'Mizan Teferi',
            'Mojo',
            'Mota',
            'Moyale',
            'Negash',
            'Negele Boran',
            'Nekemte',
            'Robe, Bale',
            'Shashamane',
            'Shire (or Inda Selassie)' .
            'Shilavo' .
            'Sodo (Wo.laita Sodo)',
            'Sodore',
            'Sokoru',
            'Tefki',
            'Tenta',
            'Tippi',
            'Tiya',
            'Tullu Milki',
            'Turmi',
            'Togo-Wochale',
            'Wacca',
            'Walwal',
            'Werder',
            'Wereta',
            'Woldia',
            'Wolaita Sodo (Sodo)',
            'Waliso',
            'Wolleka',
            'Wuchale',
            'Yabelo',
            'Yeha',
            'Yirga Alem',
            'Ziway',*/
            'Banks',
            'Insurance'
        ];
        $this->databaseSeederHelper->categorySeeder($categories, 'Supplier');
    }
}
